<?php
// module/Album/view/album/album/index.phtml:

$title = 'Countries';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<br />
<p>
    Go To:&nbsp;&nbsp;
    <a href="<?php echo $this->url('world', array('action'=>'index'));?>">"World"</a>
</p>
<br />
<p>
    <a href="<?php echo $this->url('country', array('action'=>'add'));?>">Add a New Country</a>
</p>

<table class="table">
<tr>
    <th>Country Abbr</th>
    <th>Country Name</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($countries as $country) : ?>
<tr>
    <td><?php echo $this->escapeHtml($country->abbr);?></td>
    <td><?php echo $this->escapeHtml($country->name);?></td>
    <td>
        <a href="<?php echo $this->url('country',
            array('action'=>'edit', 'id' => $country->id));?>">Edit</a>
        <a href="<?php echo $this->url('country',
            array('action'=>'delete', 'id' => $country->id));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>