<?php
// module/Album/view/album/album/index.phtml:

$title = 'Cities';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<br />
<p>
    Go To:&nbsp;&nbsp;
    <a href="<?php echo $this->url('world', array('action'=>'index'));?>">"World"</a>
</p>
<br />
<p>
    <a href="<?php echo $this->url('city', array('action'=>'add'));?>">Add a New City</a>
</p>

<table class="table">
<tr>
    <th>Country Name</th>
    <th>Country Abbreviation</th>
    <th>City Name</th>
    <th>&nbsp;</th>
</tr>
<?php foreach ($cities as $city) : ?>
<tr>
    <td><?php echo $this->escapeHtml($city["country_name"]);?></td>
    <td><?php echo $this->escapeHtml($city["country_abbr"]);?></td>
    <td><?php echo $this->escapeHtml($city["name"]);?></td>
    <td>
        <a href="<?php echo $this->url('city',
            array('action'=>'edit', 'id' => $city["id"]));?>">Edit</a>
        <a href="<?php echo $this->url('city',
            array('action'=>'delete', 'id' => $city["id"]));?>">Delete</a>
    </td>
</tr>
<?php endforeach; ?>
</table>